title: EJ | Interim / Fractional â€” CFO / CSO / CEO
description:  Championing Independent Energy, Sustainable Agriculture & Building Automation | Waste-to-X | District Heating | Biogas | BioChar | Carbon Removal
url: https://cv.h1energy.de
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
